/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hdl_btfp_Fpga */

#ifndef _Included_com_hdl_btfp_Fpga
#define _Included_com_hdl_btfp_Fpga
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hdl_btfp_Fpga
 * Method:    SetDo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hdl_btfp_Fpga_SetDo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_hdl_btfp_Fpga
 * Method:    GetDi
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hdl_btfp_Fpga_GetDi
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hdl_btfp_Fpga
 * Method:    SetSp
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hdl_btfp_Fpga_SetSp
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_hdl_btfp_Fpga
 * Method:    MotorJP
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hdl_btfp_Fpga_MotorJP
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hdl_btfp_Fpga
 * Method:    MotorJN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hdl_btfp_Fpga_MotorJN
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hdl_btfp_Fpga
 * Method:    MotorStop
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hdl_btfp_Fpga_MotorStop
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
